export const VITE_API_FIREBASE_APIKEY = import.meta.env.VITE_API_FIREBASE_APIKEY
export const VITE_API_FIREBASE_AUTH_DOMAIN = import.meta.env.VITE_API_FIREBASE_AUTH_DOMAIN
export const VITE_API_FIREBASE_PROJECT_ID = import.meta.env.VITE_API_FIREBASE_AUTH_PROJECT_ID
export const VITE_API_FIREBASE_STORAGE_BUCKET = import.meta.env.VITE_API_FIREBASE_STORAGE_BUCKET
export const VITE_API_FIREBASE_MESSAGING_SENDER_ID = import.meta.env
  .VITE_API_FIREBASE_MESSAGING_SENDER_ID
export const VITE_API_FIREBASE_APP_ID = import.meta.env.VITE_API_FIREBASE_APP_ID
